django_leavemgt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leaves.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leaves/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/employee/',
         views.employee_signup, name='employee_signup'),
    path('signup/employer/',
         views.EmployerSignUpView.as_view(), name='employer_signup'),
    path('employee/', views.employee_dashboard, name='employee_dashboard'),
    path('dashboard/', views.employer_dashboard, name='employer_dashboard'),
    path('chats/', views.inbox, name='inbox'),
    path('chat/<int:pk>/', views.chat, name='chat'),
    path('send_chat/<int:pk>/', views.send_chat, name='send_chat'),
    path('receive_msg/<int:pk>/', views.received_chat, name='received_chat'),
    path('pending-leaves/', views.pending_leaves, name='pending_leaves'),
    path('approved-leaves/', views.approved_leaves, name='approved_leaves'),
    path('rejected-leaves/', views.rejected_leaves, name='rejected_leaves'),
    path('leave/<int:pk>/', views.leave_detail, name='leave_detail'),
    path('leave/<int:pk>/delete/', views.leave_delete, name='leave_delete'),
    path('leave/<int:pk>/approve/', views.leave_approve, name='leave_approve'),
    path('leave/<int:pk>/reject/', views.leave_reject, name='leave_reject'),
    path('create-leave/', views.create_leave, name='create_leave'),
    path('json/', views.json_records, name='json_records'),
    path('', views.home, name='home'),
]

leaves/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser

from .managers import LeaveManager


class User(AbstractUser):
    is_employer = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)


class Employer(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        null=True, related_name='employer')

    def __str__(self):
        return f"Profile for {self.user.username}"


class Employee(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),)
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        null=True, related_name='employee')
    gender = models.CharField(
        max_length=10, choices=GENDER_CHOICES)

    def __str__(self):
        return f"Profile for {self.user.username}"


class Leave(models.Model):
    PENDING = 'P'
    APPROVED = 'A'
    REJECTED = 'R'
    LEAVE_STATUS = (
        (PENDING, 'Pending'),
        (APPROVED, 'Approved'),
        (REJECTED, 'Rejected'),
    )

    ANNUAL = 'annual'
    SICK = 'sick'
    SABBATICAL = 'sabbatical'
    MATERNITY = 'maternity'
    PATERNITY = 'paternity'

    LEAVE_TYPE = (
        (ANNUAL, 'Annual Leave'),
        (SICK, 'Sick Leave'),
        (SABBATICAL, 'Sabbatical Leave'),
        (PATERNITY, 'Paternity Leave'),
        (MATERNITY, 'Maternity Leave'),
    )

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='leaves')
    start_date = models.DateField(
        help_text='Leave starts on...')
    end_date = models.DateField(
        help_text='Leave ends on...')
    leave_type = models.CharField(
        max_length=50, choices=LEAVE_TYPE)
    reason = models.CharField(
        'Reason for Leave', max_length=255)
    status = models.CharField(
        max_length=1, choices=LEAVE_STATUS, default=PENDING)
    is_approved = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = LeaveManager()

    class Meta:
        ordering = ['-created']
        get_latest_by = 'created'

    def __str__(self):
        return f'{self.leave_type} - {self.user} - {self.status}'

    @property
    def leave_days(self):
        start_date = self.start_date
        end_date = self.end_date
        if start_date > end_date:
            return
        dates = (end_date - start_date)
        return dates.days

    def get_json(self):
        return {
            'user': self.user.username,
            'leave_type': self.leave_type,
            'start_date': self.start_date,
            'end_date': self.end_date,
            'leave_days': self.leave_days,
            'status': self.status,
        }

    @property
    def leave_approved(self):
        return self.is_approved == True

    @property
    def leave_pending(self):
        return self.status == 'P'

    @property
    def approve_leave(self):
        if not self.is_approved:
            self.is_approved = True
            self.status = 'A'
            self.save()

    @property
    def reject_leave(self):
        if self.is_approved or not self.is_approved:
            self.is_approved = False
            self.status = 'R'
            self.save()


class Message(models.Model):
    body = models.TextField()
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    seen = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.body

leaves/forms.py
import datetime
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

from .models import Leave, User, Message


class EmployerSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.help_text = None

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError(
                'A user with that email already exists.')
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_employer = True
        if commit:
            user.save()
        return user


class EmployeeSignUpForm(UserCreationForm):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),)
    email = forms.EmailField(required=True)
    gender = forms.ChoiceField(required=True, choices=GENDER_CHOICES)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.help_text = None

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'gender', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError(
                'A user with that email already exists.')
        return email

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_employee = True
        user.save()
        user.refresh_from_db()
        user.employee.gender = self.cleaned_data.get('gender')
        user.save()
        return user


class LeaveForm(forms.ModelForm):
    ANNUAL = 'annual'
    SICK = 'sick'
    SABBATICAL = 'sabbatical'
    MATERNITY = 'maternity'
    PATERNITY = 'paternity'

    LEAVE_TYPE = (
        (ANNUAL, 'Annual Leave'),
        (SICK, 'Sick Leave'),
        (SABBATICAL, 'Sabbatical Leave'),
        (PATERNITY, 'Paternity Leave'),
        (MATERNITY, 'Maternity Leave'),
    )

    leave_type = forms.ChoiceField(required=True, choices=LEAVE_TYPE)
    reason = forms.CharField(
        required=False, widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}))
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={
            'class': 'form-control dateinput',
            'type': 'date',
        }))
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={
            'class': 'form-control dateinput',
            'type': 'date',
        }))

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    class Meta:
        model = Leave
        fields = ['start_date', 'end_date', 'leave_type', 'reason']

    def clean_end_date(self):
        end_date = self.cleaned_data['end_date']
        start_date = self.cleaned_data['start_date']
        today_date = datetime.date.today()

        if (start_date or end_date) < today_date:
            # both dates must not be in the past
            raise forms.ValidationError(
                "Selected dates are incorrect, please select again")
        elif start_date >= end_date:
            # TRUE -> FUTURE DATE > PAST DATE,FALSE other wise
            raise forms.ValidationError("Selected dates are wrong")
        return end_date

    def clean_leave_type(self):
        try:
            end_date = self.cleaned_data['end_date']
            start_date = self.cleaned_data['start_date']
            dates = (end_date - start_date)
            leave_days = dates.days

            leave_type = self.cleaned_data['leave_type']
            
            if leave_type == Leave.PATERNITY:
                if int(leave_days) != 14:
                    raise forms.ValidationError(
                        "Paternity leave shouldn't exceed 14 days. Select new dates above.")

            if leave_type == Leave.SICK:
                if int(leave_days) != 90:
                    raise forms.ValidationError(
                        "Sick leave shouldn't exceed 90 days. Select new dates above.")

            if leave_type == Leave.ANNUAL:
                if int(leave_days) != 14:
                    raise forms.ValidationError(
                        "Annual leave shouldn't exceed 14 days. Select new dates above.")

            # if leave_type == Leave.ANNUAL:
            #     # No employee can apply for anual lave more than once
            #     if Leave.objects.filter(user=self.request.user, leave_type=Leave.ANNUAL).exists():
            #         raise forms.ValidationError('You have already applied for annual leave this year.')

        except KeyError:
            raise forms.ValidationError("An error occured.")

        return leave_type


class LeaveDeleteForm(forms.ModelForm):
    class Meta:
        model = Leave
        fields = []


class MessageForm(forms.ModelForm):
    # body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Type message here.'}))
    
    class Meta:
        model = Message
        fields = ['body']

templates/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags}}{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

templates/_chat.html
{% for chat in chats %}
{% if chat.sender == request.user and chat.receiver == contact %}
<div class="mx-1 mt-1 mb-3 overflow-hidden">
    <div style="width:46%" class="sent_msg float-end">
        <p class="rounded-3 m-0 w-100 text-white px-3 py-2">{{ chat.body }}</p>
        <span style="font-size: 12px;" class="text-muted d-block mb-2 mt-1 float-end"> {{ chat.created|time:"P" }} | {{ chat.created|date:"M Y" }}</span>
    </div>
</div>
{% elif chat.sender == contact and chat.receiver == request.user %}
<div>
    <div style="width:92%" class="d-inline-block">
        <div style="width:57%" class="received_message">
            <p class="rounded-3 m-0 w-100 px-3 py-2">{{ chat.body }}</p>
            <span style="font-size: 12px;" class="text-muted d-block mb-2 mt-1"> {{ chat.created|time:"P" }} | {{ chat.created|date:"M Y" }}</span>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}

templates/apply_leave_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Apply for Leave{% endblock %}

{% block content %}

<h1 class="mt-4">Leave Application</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="{% url 'employee_dashboard' %}">Dashboard</a></li>
    <li class="breadcrumb-item active">Apply for Leave</li>
</ol>

{% include "_alerts.html" %}

<div class="row mb-4">
    <div class="col-md-8 offset-md-2">
        <form method="post" action=".">
            {% csrf_token %}
            {{ form.start_date|as_crispy_field }}
            {{ form.end_date|as_crispy_field }}
            
            <div id="div_id_leave_type" class="mb-3">
                <label for="id_leave_type" class="form-label requiredField">
                    Leave type<span class="asteriskField">*</span>
                </label>
                <select name="leave_type" class="select form-select" id="id_leave_type">
                    <option value="annual">Annual Leave</option>
                    <option value="sick">Sick Leave</option>
                    <option value="sabbatical">Sabbatical Leave</option>
                    {% if request.user.employee.gender == 'F' %}
                    <option value="maternity">Maternity Leave</option>
                    {% else %}
                    <option value="paternity">Paternity Leave</option>
                    {% endif %}
                </select>
            </div>
            {% if form.leave_type.errors %}
            {% for error in form.leave_type.errors %} 
            <p class="text-danger fw-bold">{{ error }}</p>
            {% endfor %} 
            {% endif %}
            
            {{ form.reason|as_crispy_field }}
            <div class="submit-section">
                <button class="btn btn-primary submit-btn">Save</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script>
    document.addEventListener("DOMContentLoaded", function(event) { 
          document.querySelector(".dateinput").datepicker({ format: "yyyy/mm/dd" });
        });
</script>
{% endblock %}

templates/approved_leaves.html
{% extends "base.html" %}

{% block title %}Approved Leaves ({{ leaves.count }}){% endblock %}

{% block content %}

<h1 class="mt-4">Approved Leaves ({{ leaves.count }})</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="{% url 'employer_dashboard' %}">Dashboard</a></li>
    <li class="breadcrumb-item active">Approved Leaves ({{ leaves.count }})</li>
</ol>

<table class="table" id="approvedLeaves">
	<thead class="table-light">
        <tr>
            <th>Employee</th>
            <th>Leave Type</th>
            <th>From</th>
            <th>To</th>
            <th>No of Days</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    	{% for leave in leaves %}
        <tr>
            <td>{{ leave.user.get_full_name|default:leave.user.username|title }}</td>
            <td>{{ leave.leave_type }}</td>
            <td>{{ leave.start_date }}</td>
            <td>{{ leave.end_date }}</td>
            <td>{{ leave.leave_days }} days</td>
            <td><a href="{% url 'leave_detail' leave.pk %}">View</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock content %}

templates/chat.html
{% extends "base.html" %}

{% block title %}Chat with {{ contact.username }}{% endblock %}

{% block styles %} 
<style type="text/css">
    .messages {
        background: #fff none repeat scroll 0 0;
        width: 40%;
    }
    .chat_ib {
        width: 88%;
    }
    .chat_img {
        width: 11%;
    }
    .message {
        width: 60%;
    }
    .received_message p {
        background: #ebebeb none repeat scroll 0 0;
    }
    .sent_msg p {
        background: #05728f none repeat scroll 0 0;
    }
    .time_date {
        font-size: 12px;
    }
    .input-group input {
        background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
        font-size: 15px;
        min-height: 48px;
        outline: none;
    }
    .btn-send {
        background: #05728f none repeat scroll 0 0;
        height: 33px;
        top: 11px;
        width: 33px;
    }
</style>

{% endblock %}

{% block content %}

<!-- <h1 class="mt-4">Chat</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Chat with Employees</li>
</ol> -->

<div class="my-5 border clearfix overflow-hidden">
    <div class="messages float-start overflow-hidden border-end">
        <div class="py-2 ps-3 overflow-hidden border-bottom">
            <h5 class="m-auto text-success">Recent</h5>
        </div>
        <div style="height: 550px;" class="overflow-auto">
            {% for contact in contacts %}
            <div class="border-bottom m-0 p-3 bg-light">
                <div class="overflow-hidden clearfix">
                    <div class="chat_img float-start"> <img class="img-fluid rounded-circle" src="https://via.placeholder.com/50"
                            alt="sunil"> </div>
                    <div class="chat_ib p-0 ps-2 float-start">
                        <h6 class="mb-2">{{ contact.username|title }}</h6>
                        <p style="font-size: 14px;" class="m-auto text-muted"><a href="{% url 'chat' contact.pk %}">Chat with
                                {{ contact.username|title }}</a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="message float-start 1pt-4 px-4 pb-0">
        {% url 'inbox' as inbox_url %}{% if request.path == inbox_url %}
        You have not selected any message
        {% else %}
        <div class="py-2 mb-2 overflow-hidden border-bottom">
            <h5 class="m-auto text-success">Chats with {{ contact }}</h5>
        </div>
        <div id="chat-body" style="height: 516px;" class="overflow-auto">
            {% include '_chat.html' %}
        </div>
        <div class="position-relative border-top">
            <form id="chatForm" action="" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" name="body" id="id_body" class="border-0 text-muted w-100" placeholder="Type a message" />
                    <button class="position-absolute end-0 border-0 rounded-circle text-white btn-send" type="submit"><i class="fas fa-paper-plane"></i></button>
                </div>
            </form>
        </div>
        {% endif %}
    </div>
</div>

<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');

    let form = document.getElementById('chatForm')
    form.addEventListener('submit', sendChat)
    function sendChat(e) {
        e.preventDefault()
        let chatBody = document.getElementById('id_body').value
        const data = {
            body: chatBody
        };
        let url = "{% url 'send_chat' contact.pk %}"

        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify(data),
        })
        .then(response => response.json())
        .then(data => {
            console.log('Success:', data);
            let chat_body = document.getElementById('chat-body')
            let chatMessageBox = document.createElement('div')
            chatMessageBox.classList.add('sent_msg', 'float-end')
            chatMessageBox.innerText = data
            chat_body.append(chatMessageBox)
            document.getElementById('id_body').value=""
        })
        // .catch((error) => {
        //     console.error('Error:', error);
        // });
    }

    setInterval(receiveMessages, 2000)
    
    let counter = {{ num }}

    function receiveMessages() {
        let url = "{% url 'received_chat' contact.pk %}"
        fetch(url)
        .then(response => response.json())
        .then(data => {
            console.log('Success:', data);
            if(data.length == 0){}
            else {
                let lastMsg = data[data.length-1]
                if(counter == data.length){}
                else{
                    let chat_body = document.getElementById('chat-body')
                    let chatMessageBox = document.createElement('div')
                    chatMessageBox.classList.add('received_message')
                    chatMessageBox.innerText = data
                    chat_body.append(chatMessageBox)
                    document.getElementById('id_body').value = ""
                }
            }
            counter = data.length
        })
    }
</script>

{% endblock %}

templates/employee_dashboard.html
{% extends "base.html" %}

{% block title %}Employee: {{ request.user|title }}{% endblock %}

{% block content %}


<h1 class="mt-4">Dashboard</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">My Leaves History</li>
</ol>

{% include "_alerts.html" %}

<table class="table mb-4" id="employeeLeaves">
    <thead class="table-light">
        <tr>
            <th>Leave Type</th>
            <th>From</th>
            <th>To</th>
            <th>No of Days</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for leave in leaves %}
        <tr>
            <td>{{ leave.get_leave_type_display }}</td>
            <td>{{ leave.start_date }}</td>
            <td>{{ leave.end_date }}</td>
            <td>{{ leave.leave_days }} days</td>
            <td>{{ leave.get_status_display }}</td>
            <td><a href="{% url 'leave_detail' leave.pk %}">View</a></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="6">You have yet to apply for a Leave.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/employer_index.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}

<h1 class="mt-4">Dashboard</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Employee Leaves History</li>
</ol>
<div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body">Pending Leaves</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{% url 'pending_leaves' %}">View All</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">Approved Leaves</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{% url 'approved_leaves' %}">View All</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body">Rejected Leaves</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{% url 'rejected_leaves' %}">View All</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
</div>

<table class="table" id="allLeaves">
	<thead class="table-light">
        <tr>
            <th>Employee</th>
            <th>Leave Type</th>
            <th>From</th>
            <th>To</th>
            <th>No of Days</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <!-- Comment this line if you want to get response from JSON -->
    <tbody>
    	{% for leave in leaves %}
        <tr>
            <td>{{ leave.user.username|title }}</td>
            <td>{{ leave.get_leave_type_display }}</td>
            <td>{{ leave.start_date }}</td>
            <td>{{ leave.end_date }}</td>
            <td>{{ leave.leave_days }} days</td>
            <td>{{ leave.get_status_display }}</td>
            <td><a href="{% url 'leave_detail' leave.pk %}">View</a></td>
        </tr>
        {% endfor %}
    </tbody>

</table>


{% endblock content %}

templates/leave_delete_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Delete {{ leave.user|title }} Leave Request{% endblock %}

{% block content %}

<h1 class="mt-4">Delete {{ leave.user|title }} Leave Request</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Dashboard</a></li>
    <li class="breadcrumb-item active">Delete Leave Request</li>
</ol>

<form action="" method="post">
{% csrf_token %}

{{ form }}
<p>Are you sure you want to delete this <a href="{% url 'leave_detail' leave.pk %}">leave request</a>?</p>

<button class="btn btn-danger" type="submit">Delete</button>
<a class="btn btn-primary" href="{% url 'leave_detail' leave.pk %}">Cancel</a>
</form>

{% endblock %}

templates/leave_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{ leave.user|title }} Leave Request{% endblock %}

{% block content %}

<h1 class="mt-4">{{ leave.user|title }} Leave Request</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Dashboard</a></li>
    <li class="breadcrumb-item active">Leave Request</li>
</ol>

{% include "_alerts.html" %}

<div class="row mb-5">
    <div class="col-md-8 offset-md-2">
        <div class="card mb-2">
            <div class="card-header">
                Featured
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Start Date
                    <span>{{ leave.start_date }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    End Date
                    <span>{{ leave.end_date }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Number of days
                    <span>{{ leave.leave_days }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Leave Type
                    <span>{{ leave.get_leave_type_display }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Reason
                    <span>{{ leave.reason }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Status
                    <span>{{ leave.get_status_display }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Request sent on
                    <span>{{ leave.created|date:"F j, Y" }}</span>
                </li>
            </ul>
        </div>

        {% if request.user.is_employer %}
        <div class="btn-group btn-group-justified">
            {% if leave.leave_pending %}
            <a href="{% url 'leave_approve' leave.pk %}" class="btn btn-success">Approve Request</a>
            <a href="{% url 'leave_reject' leave.pk %}" class="btn btn-danger">Reject Request</a>
            {% endif %}
        </div>
        {% else %}
            <a href="{% url 'leave_delete' leave.pk %}" class="btn btn-danger">Cancel Request</a>
        {% endif %}
    </div>
</div>                              
{% endblock %}

templates/pending_leaves.html
{% extends "base.html" %}

{% block title %}Pending Leaves ({{ leaves.count }}){% endblock %}

{% block content %}

<h1 class="mt-4">Pending Leaves ({{ leaves.count }})</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="{% url 'employer_dashboard' %}">Dashboard</a></li>
    <li class="breadcrumb-item active">Pending Leaves ({{ leaves.count }})</li>
</ol>

<table class="table" id="pendingLeaves">
	<thead class="table-light">
        <tr>
            <th>Employee</th>
            <th>Leave Type</th>
            <th>From</th>
            <th>To</th>
            <th>No of Days</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    	{% for leave in leaves %}
        <tr>
            <td>{{ leave.user.get_full_name|default:leave.user.username|title }}</td>
            <td>{{ leave.leave_type }}</td>
            <td>{{ leave.start_date }}</td>
            <td>{{ leave.end_date }}</td>
            <td>{{ leave.leave_days }} days</td>
            <td><a href="{% url 'leave_detail' leave.pk %}">View</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock content %}